version: "3.8"
services:
  postgres:
    image: postgres:15.6
    command: postgres -c 'max_connections=200'
    restart: always
    environment:
      - POSTGRES_USER=hatchet
      - POSTGRES_PASSWORD=hatchet
      - POSTGRES_DB=hatchet
    ports:
      - "5432:5432"
    volumes:
      - hatchet_postgres_data:/var/lib/postgresql/data

volumes:
  hatchet_postgres_data:
